import { coupleShellPatches, coupleTwoCLTWalls } from "../coupling";

describe("CLT wall coupling", () => {
  test("welds coincident interface nodes between two walls", () => {
    const wallA = {
      nodes: [
        [0, 0, 0],
        [0, 2, 0],
        [0, 2, 3],
        [0, 0, 3],
      ] as [number, number, number][],
      elements: [
        [0, 1, 2],
        [0, 2, 3],
      ],
    };
    const wallB = {
      nodes: [
        [0, 2 + 1e-5, 0],
        [0, 4, 0],
        [0, 4, 3],
        [0, 2 - 1e-5, 3],
      ] as [number, number, number][],
      elements: [
        [0, 1, 2],
        [0, 2, 3],
      ],
    };

    const coupled = coupleTwoCLTWalls(wallA, wallB, 1e-4);

    expect(coupled.nodes.length).toBe(6);
    expect(coupled.elements.length).toBe(4);
    expect(coupled.wallBNodeMap[0]).toBe(coupled.wallANodeMap[1]);
    expect(coupled.wallBNodeMap[3]).toBe(coupled.wallANodeMap[2]);
  });

  test("keeps walls uncoupled when tolerance is too small", () => {
    const wallA = {
      nodes: [
        [0, 0, 0],
        [0, 2, 0],
        [0, 2, 3],
        [0, 0, 3],
      ] as [number, number, number][],
      elements: [
        [0, 1, 2],
        [0, 2, 3],
      ],
    };
    const wallB = {
      nodes: [
        [0, 2 + 1e-5, 0],
        [0, 4, 0],
        [0, 4, 3],
        [0, 2 - 1e-5, 3],
      ] as [number, number, number][],
      elements: [
        [0, 1, 2],
        [0, 2, 3],
      ],
    };

    const coupled = coupleTwoCLTWalls(wallA, wallB, 1e-7);

    expect(coupled.nodes.length).toBe(8);
    expect(coupled.elements.length).toBe(4);
  });

  test("drops degenerate elements generated by node welding", () => {
    const patchA = {
      nodes: [
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
      ] as [number, number, number][],
      elements: [[0, 1, 2]],
    };
    const patchB = {
      nodes: [
        [0, 0, 0],
        [1, 0, 0],
        [1, 0, 1e-8],
      ] as [number, number, number][],
      elements: [[0, 1, 2]],
    };

    const coupled = coupleShellPatches([patchA, patchB], 1e-4);

    expect(coupled.elements.length).toBe(1);
    expect(coupled.elementMaps[0]).toHaveLength(1);
    expect(coupled.elementMaps[1]).toHaveLength(0);
  });
});
